export type BookSourceFormat = 'gutenberg-json' | 'unavailable';

export type BookCatalogEntry = {
  id: string;
  title: string;
  author: string;
  sourceLanguage: string;
  synopsis: string;
  totalChapters: number;
  isBundled: boolean;
  sourceFormat: BookSourceFormat;
};

export type BookPage = string[]; // ordered paragraphs

export type BookChapter = {
  index: number;
  title: string;
  pages: BookPage[];
};

export type IngestedBook = {
  id: string;
  title: string;
  author: string;
  sourceLanguage: string;
  synopsis: string;
  totalChapters: number;
  isBundled: boolean;
  chapters: BookChapter[];
};

// The Library shelf needs title/author/synopsis for every book up front, but
// full chapter text (megabytes per book — Anna Karenina alone is ~2MB of JSON)
// should never be parsed until a book is actually opened. manifest.json holds
// only the lightweight fields, generated by scripts/ingest-books.mjs alongside
// each book's full-text JSON — this file is the single source of truth for it.
// eslint-disable-next-line @typescript-eslint/no-var-requires
export const BOOK_CATALOG: BookCatalogEntry[] = require('../../../assets/books/manifest.json');

// Metro requires static require() paths, so each bundled book's full text is
// mapped explicitly rather than loaded by dynamic id. Add an entry here
// whenever scripts/ingest-books.mjs produces a new book JSON. Wrapping each
// require() in a thunk defers the actual JSON parse until that specific book
// is opened — the eager version of this (parsing all 5 books' full text at
// import time) was the main cause of startup and navigation jank.
const BUNDLED_BOOK_LOADERS: Record<string, () => IngestedBook> = {
  'pride-and-prejudice': () => require('../../../assets/books/pride-and-prejudice.json'),
  'don-quixote': () => require('../../../assets/books/don-quixote.json'),
  'the-odyssey': () => require('../../../assets/books/the-odyssey.json'),
  'anna-karenina': () => require('../../../assets/books/anna-karenina.json'),
  'crime-and-punishment': () => require('../../../assets/books/crime-and-punishment.json'),
};

// Caches the parsed book after first load — re-opening a book (e.g. navigating
// back into the Reader) is then just a Map lookup, not a re-parse.
const bookCache = new Map<string, IngestedBook>();

export function getBundledBookText(bookId: string): IngestedBook | null {
  const cached = bookCache.get(bookId);
  if (cached) return cached;

  const load = BUNDLED_BOOK_LOADERS[bookId];
  if (!load) return null;

  const book = load();
  bookCache.set(bookId, book);
  return book;
}
